### ISSUE TITLE
Fix docker issues

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicDataAnalyses#35]
Docker needs update

**Comment by lwaldron** [comment]
I tried to simplify things by using ghcr.io instead of DockerHub, since it doesn't require creating authentication keys, but now there are new problems (https://github.com/waldronlab/curatedMetagenomicDataAnalyses/runs/6427183639?check_suite_focus=true). Would you take a look and try to get the GHA Docker build working @jwokaty ?

**Comment by jwokaty** [comment]
Close #44
